name: 'GitHub Action for Firebase with JDK'
author: 'Jeremy Shore'
description: 'Wraps the firebase-tools CLI and JDK to enable common commands and run firebase emulator.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
