name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: w9jds
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: w9jds/firebase-action:latest
